name = "fpm"
version = "0.12.0"
license = "MIT"
author = "fpm maintainers"
maintainer = "@fortran-lang/fpm"
copyright = "2020-2025 fpm contributors"
homepage = "https://fpm.fortran-lang.org/"
description = "Fortran Package Manager"

[preprocess]
[preprocess.cpp]
macros=["FPM_RELEASE_VERSION={version}"]

[dependencies]
toml-f.git = "https://github.com/jinangshah21/toml-f.git"
toml-f.rev = "38c294fc5d9cb5fa6a9d3569514da28b8705f3fb"
M_CLI2.git = "https://github.com/jinangshah21/M_CLI2.git"
M_CLI2.rev = "92bbbc3b2c455543fddb4104043a513d9d359fbe"
fortran-regex.git  = "https://github.com/perazz/fortran-regex"
fortran-regex.tag  = "1.1.2"
jonquil.git = "https://github.com/jinangshah21/jonquil.git"
jonquil.rev = "108494ec479395e490d6304ee8542eeb0fb04afa"
fortran-shlex.git = "https://github.com/jinangshah21/fortran-shlex"
fortran-shlex.rev = "a030f1b9754ac3e6c5aa17fed01e5c2d767b947b"

[[test]]
name = "cli-test"
source-dir = "test/cli_test"
main = "cli_test.f90"

[[test]]
name = "new-test"
source-dir = "test/new_test"
main = "new_test.f90"

[[test]]
name = "fpm-test"
source-dir = "test/fpm_test"
main = "main.f90"

[[test]]
name = "help-test"
source-dir = "test/help_test"
main = "help_test.f90"

