name = "fpm"
version = "0.12.0"
license = "MIT"
author = "fpm maintainers"
maintainer = "@fortran-lang/fpm"
copyright = "2020-2025 fpm contributors"
homepage = "https://fpm.fortran-lang.org/"
description = "Fortran Package Manager"

[preprocess]
[preprocess.cpp]
macros=["FPM_RELEASE_VERSION={version}"]

[dependencies]
toml-f.git = "https://github.com/jinangshah21/toml-f.git"
toml-f.rev = "65ef20430e2543ac89a5558a11ae1c8404d46763"
M_CLI2.git = "https://github.com/jinangshah21/M_CLI2.git"
M_CLI2.rev = "edf5c93091ff257eeefb916045ab47d76a3c358e"
fortran-regex.git  = "https://github.com/jinangshah21/fortran-regex.git"
fortran-regex.rev  = "c3807f49bf3a88df9b1527b2c49fc956abb77398"
jonquil.git = "https://github.com/jinangshah21/jonquil.git"
jonquil.rev = "1055a955a87fd16f88be93a4779cee54fdb2c70a"
fortran-shlex.git = "https://github.com/perazz/fortran-shlex"
fortran-shlex.rev = "e20b6f86c82e33fae78b54b074bab5369efde6a3"

[[test]]
name = "cli-test"
source-dir = "test/cli_test"
main = "cli_test.f90"

[[test]]
name = "new-test"
source-dir = "test/new_test"
main = "new_test.f90"

[[test]]
name = "fpm-test"
source-dir = "test/fpm_test"
main = "main.f90"

[[test]]
name = "help-test"
source-dir = "test/help_test"
main = "help_test.f90"

